const content = [
  {
    date: '2025-11-13',
    logs: [
      'clear application cache button',
    ],
  },
  {
    date: '2025-11-12',
    logs: [
      'edit recipe: save button styling',
    ],
  },
  {
    date: '2025-11-11',
    logs: [
      'nav bar has same container width as main content',
      'edit recipe: making save button stick to bottom',
      'formatting api/tags',
      'server-side caching',
    ],
  },
  {
    date: '2025-11-10',
    logs: [
      'checkbox styling',
    ],
  },
  {
    date: '2025-11-05',
    logs: [
      'restyling pin button',
      'recipes pg: pinned recipes restyling',
      'edit recipe pg: remove pin check',
      'pin button minor style changes',
    ],
  },
  {
    date: '2025-11-04',
    logs: [
      'PinCheck improvements',
      'add pin to recipe page',
    ],
  },
  {
    date: '2025-11-03',
    logs: [
      'md checkboxes',
    ],
  },
  {
    date: '2025-11-01',
    logs: [
      'making new & edit recipe pgs wider',
      'new/edit recipe pg: description textareas restyling',
      'adding missing name attr on search input',
      'bug: clear search X is misaligned',
      'custom 404 page',
      'footer (sp): x padd sb aligned w content above',
      'bug: edit recipe pg: pin btn sb same width always',
      'bug: clear search X is misaligned',
      'bugfix: recipes not wrapping correctly',
      'create/edit tag pg: shrink description textarea',
      'create/edit recipe pg: stack textareas',
      'change edit button text',
      'tag pg: recipe list needs inner spacing',
      'date: add ml-auto',
      'cookCounter btn: add ml-auto',
    ],
  },
  {
    date: '2025-10-28',
    logs: [
      'checkpist typo',
      'recipe pg: adding comments',
    ],
  },
  {
    date: '2025-10-25',
    logs: [
      'adding CookCounterButton component',
      'cook counter - add to recipe list screen',
      'cook counter BE & UI changes',
    ],
  },
  {
    date: '2025-10-24',
    logs: [
      'cook counter UI',
    ],
  },
  {
    date: '2025-10-21',
    logs: [
      'adding shadow to search box',
    ],
  },
  {
    date: '2025-10-20',
    logs: [
      'adding footer',
      'removing hamburger menu',
    ],
  },
  {
    date: '2025-10-19',
    logs: [
      'adding change log page',
      'adding settings page placeholder',
      'adding hamburger menu',
      'changing search result text',
      'various style changes',
      'making the recipes page the main page',
      'updating pinned recipes break style',
      'adding pinned recipes',
    ],
  },
  {
    date: '2025-10-18',
    logs: [
      'search improvement',
      'sorting tags on recipe page',
      'sorting tags on recipe card',
      'sorting recipes by date (tags page)',
      'adding date on recipe card',
      'sorting recipes by date',
      'fix tags page typo',
      'max container width',
    ],
  },
  {
    date: '2025-08-11',
    logs: [
      'meta title hook',
      'increasing retry delay',
      'new recipe auto focus on title field',
      'new recipe formatting',
      'changing edit tag text',
    ],
  },
  {
    date: '2025-08-10',
    logs: [
      'retry delay constant',
      'shared findRecipe function',
      'recipe page fix',
    ],
  },
  {
    date: '2025-08-09',
    logs: [
      'adding target blank to link',
      'recipe page: removing fetch single recipe',
    ],
  },
  {
    date: '2025-08-05',
    logs: [
      'new recipe: decrease textarea heights',
      'replacing uid field on new recipe/tag pages',
      'add fallback for recipe page',
      'a tag -> Link',
      'rearranging fetch order',
      'improving comments',
      'remove swr fallbacks',
    ],
  },
  {
    date: '2025-08-02',
    logs: [
      'edit tag: show warning if title exists already',
      'new tag: show warning if title exists already',
      'precvent deleting a tag if it\'s used in a recipe',
      'improving getRecipesByTag',
      'removing ability to edit uid at recipe/tag creation',
      'shared uid display cnt',
      'adding \'Page\' to cnt names',
      'tag pg: adding tag data caching',
      'recipe pg: adding recipe data caching',
      'adding optional fallbackData to useData hook',
      'minor improvements to getAllRecipes and getAllTags',
    ],
  },
  {
    date: '2025-08-01',
    logs: [
      'recipes pg: container height',
      'recipes pg: change bg color',
      'recipes pg: make container height full',
      'search: restyle matches list',
      'search: show what matched',
      'search: add clear text button',
      'simple search',
      'change background color',
      'fixing blank new tag',
      'color picker',
    ],
  },
  {
    date: '2025-07-31',
    logs: [
      'new tag: color picker',
      'recipe pg: tag ui fixes',
      '[swr] edit tag pg',
      '[swr] new tag pg',
      '[swr] tags pg',
      'creating shared initialValues',
      '[swr] edit recipe pg',
      'shared useData hook',
      '[swr] new recipe pg',
      'creating shared constants file',
      '[swr] recipes pg',
      '[swr] recipe pg',
      'install swr',
    ],
  },
  {
    date: '2025-07-30',
    logs: [
      'improving SubmitButton',
      'update meta data',
      'recipe pg: add count of recipes for each tag',
      'tags pg: add recipe counts',
      'change Tag component to accept children',
      'view tag pg: display count of recipes',
      'move getRecipesByTag to shared util',
      'recipe card: show if a recipe has no content',
      'view recipe: add some padding above the Add content link',
      'creating shared RecipeCard',
      'some cleanup',
      'new tag: make description field shorter',
      'removing dynamoTypes',
      'new tag page',
      'view tags page: more ui changes',
      'view recipe page: more ui changes',
      'recipes page: adding arrow on card link',
      'view page: remove top margin on description',
    ],
  },
  {
    date: '2025-07-28',
    logs: [
      'adding .env example file',
      'explicitly require creds from env variables',
      'adding killswitch',
      'temporarily disable logger',
      'improve logging middleware',
    ],
  },
  {
    date: '2025-07-27',
    logs: [
      'view tag page: title styling',
      'view tags page: fixing spacing on sp',
      'view tags page: moving new tag link to top',
      'view tags page: removing heading',
      'edit tag page',
      'view tag page: adding edit link',
      'view recipe page: adjusting margins',
      'adding mini tag styles into shared',
      'tags page: restyling & removing editing logic',
      'removing unused class',
      'decrease md hr margins',
      'recipe list page: restyling',
      'moving getTitleByUid into shared util',
      'recipes page: sort list by title',
      'edit recipe page: moving save button to top',
      'new recipe page: increasing textarea heights',
      'add optional styles on Submit button',
      'view recipe page: changing conditional rendering',
      'global style override for images',
      'clenaing public folder',
      'adding logging middleware',
      'auth middleware improvements',
      'deleting the global form data type',
      'cleaning up the global types',
    ],
  },
  {
    date: '2025-07-26',
    logs: [
      'view recipe page: fix title and edit link alignment',
      'edit recipe page: make text areas taller on sp',
      'edit recipe page: restyle uid field',
      'SharedButton disabled prop should be optional',
      'remove ref param',
      'view recipe page spacing adjustments',
      'remove scrollbar on tags list',
      'move delete button into edit page',
      'move edit link up next to title',
      'various tag design changes',
      'adding disabled styled to SharedButton',
      'view recipe ingredients and instructions spacing adjustments',
      'make markdown links blue',
      'improving error messages',
      'improving error message style',
    ],
  },
  {
    date: '2025-07-25',
    logs: [
      'view recipe page: ui changes',
      'adding more global style overrides',
    ],
  },
  {
    date: '2025-07-24',
    logs: [
      'removing todos',
      'view recipe ui changes',
      'new recipe page: new tag text should be left aligned',
      'view recipe page: remove headings',
      'view recipe page ui changes',
      'tailwind overrides',
      'add url param to focus on input',
      'view recipe page: tags show title not uid',
      'restyling tags',
      'view recipe page: restyling edit & delete buttons',
      'adding global padding bottom to body',
      'adjusting edit recipe page mobile padding',
      'adjusting new recipe page mobile padding',
      'adjusting recipe page mobile padding',
      'adjusting tw list top margin',
      'fix recipe page reference section styles',
      'fix recipe page description full width',
    ],
  },
  {
    date: '2025-07-23',
    logs: [
      'cleaning up api functions',
      'various cleanup',
      'adding missing types',
      'removing auto complete on new tag input',
      'add auto complete on tag inputs',
      'moving styles into TagButton',
      'creating TagButton component',
      'add new tag directly in the tags component',
    ],
  },
  {
    date: '2025-07-22',
    logs: [
      'moving getNewId into shared file',
      'errorMessages.ts',
    ],
  },
  {
    date: '2025-07-21',
    logs: [
      'add sort order for recipes and tags',
      'removing blank space if no tags on recipe page',
      'putting back the 2-col form design for mobile',
      'removin g dark mode',
      'adding safety for when Japanese characters are passed to generate a uid',
      'adding required fields to new recipe form',
      'fixing errors',
      'basic mobile friendliness',
      'tags page restyling',
      'tag paeg restyling',
      'recipe page restyling',
      'changing selected nav item color',
      'Tag component style improvements',
      'SharedHeading improvements',
      'fixing markdown',
      'recipe edit page style enhancements',
      'check if uid exists before creating',
      'new recipe page restyling',
      'adding optional classes to TextAreaField',
      'remove button to new recipe on recipes page',
      'SharedHeading styles',
      'new loader style',
      '[bug] fix lost uid on tag edit',
      'tags page style improvements',
      'recipe page style improvements',
      'recipes page style improvements',
      'InputField improvements',
      'tags page style improvements',
      'making InputField label optional',
      'navbar styling',
      'edit tag',
    ],
  },
  {
    date: '2025-07-20',
    logs: [
      'delete tag',
      'create new tag',
      'moving to shared button',
      'shared button',
      'fetch tags from db',
      'move tags to db',
      'improvements',
      'edit recipe',
      'SubmitButton improvements',
      'getOneRecipe minor improvement for readability',
      'delete recipe',
      'create shared link component',
    ],
  },
  {
    date: '2025-07-19',
    logs: [
      'fixing new recipe routing',
      'create shared heading component',
      'style updates on recipe page',
      'style updates on recipes page',
      'renaming sharedStyles.ts => sharedFormStyles.ts',
      'updating new-recipe page styles',
      'create shared input styles',
      'update home page',
      'updating readme',
      'add link to backlog in readme',
      '[bug] fixing loading state on tag page',
      '[bug] fixing loading state on new-recipe page',
    ],
  },
  {
    date: '2025-03-20',
    logs: [
      'renaming cnt Loading => LoadingMessage',
      'adding shared ErrorMessage cnt',
      'adding shared Loading cnt',
      'restyling home page',
      'fixing navbar home link',
      'auth middleware cleanup',
      'redirecting \'/\' to \'/home\'',
      'adding basic auth',
    ],
  },
  {
    date: '2025-03-04',
    logs: [
      'updating favicon',
    ],
  },
  {
    date: '2025-03-01',
    logs: [
      'renaming repo',
    ],
  },
  {
    date: '2025-02-22',
    logs: [
      'GET and POST recipes',
      'new recipe form',
    ],
  },
  {
    date: '2025-02-17',
    logs: [
      'connecting to DynamoDB',
    ],
  },
  {
    date: '2025-02-16',
    logs: [
      'new folder structure',
      'removing console.log',
    ],
  },
  {
    date: '2025-02-11',
    logs: [
      'add error messages file',
      'adding form functionality',
      'adding helper file',
      'adding tags checkboxes',
      'adding DateField and TextAreaField',
      'adding shared api fetch helper',
      'adding documentation',
      'cleaning up mock',
      'cleaning up types',
      'adding tags',
      'adding add-new button',
      'style changes',
      'adding react-markdown',
    ],
  },
  {
    date: '2025-02-09',
    logs: [
      'adding mock data and navbar',
      'adding recipe pages',
      'adding about page',
      'Initial commit from Create Next App  ',
    ],
  },
]

export default content;
