import { Providers } from './providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import LayoutUI from './LayoutUI';

import './globals.css';
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spud2Gut',
  description: 'Recipe app, generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen antialiased ${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <LayoutUI>{children}</LayoutUI>
        </Providers>
      </body>
    </html>
  );
}
