import { Providers } from './providers';
import type { Metadata } from 'next';
import { QueryClient, dehydrate, HydrationBoundary } from '@tanstack/react-query';
import { fetchJSON } from '@/lib/fetchJSON';
import { queryKeys } from '@/lib/queryKeys';
import { Geist, Geist_Mono } from 'next/font/google';
import LayoutUI from './LayoutUI';

import './globals.css';
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spud2Gut',
  description: 'Recipe app, generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery({
      queryKey: queryKeys.tags,
      queryFn: () => fetchJSON('/api/tags'),
    }),
    queryClient.prefetchQuery({
      queryKey: queryKeys.recipes,
      queryFn: () => fetchJSON('/api/recipes'),
    }),
  ]);

  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen antialiased ${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <HydrationBoundary state={dehydratedState}>
            <LayoutUI>{children}</LayoutUI>
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
